# Users module configuration
defaultGroups:
  - wheel
  - adm
  - audio
  - cdrom
  - dialout
  - floppy
  - video
  - plugdev
  - netdev
  - bluetooth
  - power

autologin: false
sudoersGroup: "sudo"
requirePasswordField: true
userShell: "/bin/bash"
hostname: "eloquence"
