[LightDM]
start-default-seat=true

[Seat:*]
autologin-user=eloquence
autologin-user-timeout=0
autologin-session=cinnamon
autologin-insecure=true
pam-autologin-service=lightdm-autologin
user-session=cinnamon
greeter-show-manual-login=false
greeter-hide-users=false
