# Partitioning module configuration
efiSystemPartition: "/boot/efi"
userSwapChoices:
  - none
  - small
  - suspend
  - file

initialPartitioningChoice: erase
partitionLayout:
  - name: "root"
    filesystem: "ext4"
    mountPoint: "/"
    size: 100%
