---
dontChroot: false
timeout: 30
script:
  - command: "rm -f /usr/share/applications/install-eloquence.desktop /etc/skel/Desktop/install-eloquence.desktop /home/* /Desktop/install-eloquence.desktop /home/*/.config/autostart/install-eloquence.desktop"
