# Welcome module configuration
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
  requiredStorage: 15         
  requiredRam: 2.0             
  internetCheckUrl: "http://detectportal.firefox.com/success.txt"
  check:
    - storage
    - ram
    - power
    - internet
