sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partitioning
    - users
    - summary
  - exec:
    - partition
    - unpack
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - grubcfg
    - bootloader
    - removeuser
    - shellprocess
    - packages
    - finished
  - show:
    - finished

branding: eloquence
prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
